### ISSUE TITLE
安装程序不能识别自带硬盘

### ISSUE THREAD

**Issue by lichuanyu** [VanXNF/Hackintosh-Acer-Swift3-SF313-52#1]
硬盘品牌是金士顿
mac 磁盘工具无法识别nvme盘

**Comment by Fireflies** [comment]
> 硬盘品牌是金士顿
> mac 磁盘工具无法识别nvme盘

一样的问题，后来查看bios发现sata mode是optane without raid，不是ahci，估计和这个有关系。但是sata mode好像改不了

**Comment by lichuanyu** [comment]
设置bios密码后可以更改,晚上我再看下bios设置

**Comment by Fireflies** [comment]
> 设置bios密码后可以更改,晚上我再看下bios设置

我这边管理密码和用户密码都设置了，但是改不了sata mode，只开放了安全启动的修改权限

**Comment by lichuanyu** [comment]
我bios都没那个选项

**Comment by VanXNF** [comment]
可以更改的，在启动进入 BIOS 后，切换到第二个标签页，按下 ctrl + S，就会出现切换 SATA MODE 选项的设置了 @lichuanyu @Fireflies

**Comment by lichuanyu** [comment]
好的,高端bios

**Comment by lichuanyu** [comment]
这边已经安装上了
