### ISSUE TITLE
OC是什么版本？OS是什么版本？BIOS如何做设置？

### ISSUE THREAD

**Issue by shihengs** [VanXNF/Hackintosh-Acer-Swift3-SF313-52#3]

**Comment by VanXNF** [comment]
你好，这个机子我给家人做上网本了，因此已经没在研究这个EFI，所以你这些问题可以查看一下[第二个issue](https://github.com/VanXNF/Hackintosh-Acer-Swift3-SF313-52/issues/2)，那个 issue 下有人宣称已经解决这些问题了。
