### ISSUE TITLE
安装上了，有如下问题，求助！

### ISSUE THREAD

**Issue by shihengs** [VanXNF/Hackintosh-Acer-Swift3-SF313-52#4]
1，检测不到声卡
2，检测不到无线网卡，但是可以驱动蓝牙
3，睡眠就醒不过来
第三个问题不重要，请问前两个问题怎么解决？

**Comment by shihengs** [comment]
MacOS版本为10.15.7

**Comment by VanXNF** [comment]
你好，这个机子我给家人做上网本了，因此已经没在研究这个EFI，所以你这些问题可以查看一下[第二个issue](https://github.com/VanXNF/Hackintosh-Acer-Swift3-SF313-52/issues/2)，那个 issue 下有人宣称已经解决这些问题了。
