### ISSUE TITLE
借地方问下各位大佬

### ISSUE THREAD

**Issue by shubolab** [VanXNF/Hackintosh-Acer-Swift3-SF313-52#5]
想问下大家bios好多地方都锁死了，怎么解呢？比如切换UEFI还是传统引导那个地方都直接是灰色的。。。

另外还有大家有mkey的nvme硬盘能正常使用的嘛，不想删掉原来预装的Windows系统，用了一个闲置的东芝p2000 1TB nvme硬盘来代换，结果BIOS里直接不识别。。。

**Comment by lckei** [comment]
biso里面要关了 RTS optane without raid / optan with raid 选项 改回ACHI 就可以了，一般进BIOS 用 ctrl +s  就可以打开这个隐藏选项。

**Comment by lnxyz** [comment]
> 想问下大家bios好多地方都锁死了，怎么解呢？比如切换UEFI还是传统引导那个地方都直接是灰色的。。。
> 
> 另外还有大家有mkey的nvme硬盘能正常使用的嘛，不想删掉原来预装的Windows系统，用了一个闲置的东芝p2000 1TB nvme硬盘来代换，结果BIOS里直接不识别。。。


biso里面要关了 RTS optane without raid / optan with raid 选项 改回ACHI 就可以了，一般进BIOS 用 ctrl +s 就可以打开这个隐藏选项。

**Comment by kennethBo** [comment]
> 

感谢回复，我之后试一试

**Comment by shubolab** [comment]
okay, 我之后试试

**Comment by shubolab** [comment]
> > 想问下大家bios好多地方都锁死了，怎么解呢？比如切换UEFI还是传统引导那个地方都直接是灰色的。。。
> > 另外还有大家有mkey的nvme硬盘能正常使用的嘛，不想删掉原来预装的Windows系统，用了一个闲置的东芝p2000 1TB nvme硬盘来代换，结果BIOS里直接不识别。。。
> 
> biso里面要关了 RTS optane without raid / optan with raid 选项 改回ACHI 就可以了，一般进BIOS 用 ctrl +s 就可以打开这个隐藏选项。

nb 确实可以
